name: Feature Request
description: Suggest a new feature or enhancement for Cortex
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! We appreciate your input in making Cortex better.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What frustration or limitation are you experiencing?
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: "I would like..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "I tried... but..."

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - CLI
        - MCP Server
        - VS Code Extension
        - Core Storage
        - Documentation
        - Multiple Components
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would significantly improve my workflow
        - High - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific scenario where this feature would be useful
      placeholder: |
        As a developer working on multiple projects...
        I want to...
        So that...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature might work (CLI commands, code snippets, UI mockups, etc.)
      placeholder: |
        ```bash
        cortex feature-example
        ```
      render: markdown

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request
      placeholder: "Links to similar features in other tools, mockups, etc."

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have clearly described the problem and proposed solution
          required: true
        - label: This feature aligns with Cortex's core purpose (persistent memory for AI tools)
          required: true
